import os
import re
import time
import shutil
from WingLoop_Library import Aswing_Director


import subprocess
import glob




__all__ = [
    "VideoPlot_Generate_postscript_file",
    "Generate_Analysis_Videos",
    "Generate_Strobe_Plot",
]



def VideoPlot_Generate_postscript_file(
    geometry_filename,
    reference_folder,
    input_files,
    video_folder,
    aswing_alias="aswing_stable",
    stable_duration=1.0,
    poll_interval=0.1,
    timeout=30
):
    """
    Launches ASWING, loads a geometry and its associated files, enters OPER mode,
    lets the user issue commands interactively, then captures the resulting plot.ps
    and moves it to the video folder.

    Parameters
    ----------
    geometry_filename : str        - e.g. "aircraft_L20_K0.01_FWT0.4.asw"
    reference_folder  : str        - folder containing the geometry and input files
    input_files       : list[str]  - ordered list of files to load (point, settings, results…)
    video_folder      : str        - destination folder for the output .ps file
    aswing_alias      : str        - shell alias or path for the ASWING executable
    stable_duration   : float      - seconds plot.ps must be unchanged to be considered done
    poll_interval     : float      - seconds between stability checks
    timeout           : float      - max seconds to wait for plot.ps before raising TimeoutError

    Returns
    -------
    target_ps : str - absolute path of the moved .ps file
    """
    base_dir = os.getcwd()

    # ── Output folder (created before ASWING shifts CWD) ──────────────────
    target_dir = os.path.join(base_dir, video_folder)
    os.makedirs(target_dir, exist_ok=True)
    print(f"[ASW_Helpers] Output folder ready: {target_dir}")

    # ── Launch ASWING ──────────────────────────────────────────────────────
    print(f"[ASW_Helpers] Starting ASWING with geometry: {geometry_filename}")
    ASW_handler = Aswing_Director(
        aswing_path=None,
        aswing_alias=aswing_alias,
        wait_time=0.03,
        finished_writing_file_check_timestep=0.001
    )
    ASW_handler.start_aswing(
        directory=reference_folder,
        filename=geometry_filename,
        print_output=True
    )

    # ── Load all provided input files ──────────────────────────────────────
    print(f"[ASW_Helpers] Loading {len(input_files)} input file(s)...")
    for f in input_files:
        print(f"[ASW_Helpers]   → {f}")
        ASW_handler.Load_Files_ASW(f)

    # ── Enter OPER and interactive loop ────────────────────────────────────
    print(f"[ASW_Helpers] Entering OPER mode...")
    ASW_handler.send_command_and_receive("OPER")

    print()
    print("=" * 60)
    print("[ASW_Helpers] INTERACTIVE MODE")
    print("  You can now modify how the video is generated by ASWING.")
    print("  Send any ASWING command to adjust plot settings, views,")
    print("  or animation parameters before the hardcopy is triggered.")
    print("  When you are satisfied with the configuration, type Y to")
    print("  proceed with the hardcopy and generate the postscript file.")
    print("=" * 60)
    print()

    while True:
        ii = input("  [ASW_Helpers] (Y to proceed with hardcopy): ")
        if ii.strip().upper() == "Y":
            break
        ASW_handler.send_command_and_receive(ii)

    print()

    # ── Trigger hardcopy ───────────────────────────────────────────────────
    print("[ASW_Helpers] Triggering hardcopy sequence...")
    ASW_handler.send_command_and_receive("O")
    ASW_handler.send_command_and_receive("H")
    ASW_handler.send_command_and_receive(" ")
    ASW_handler.send_command_and_receive(".")
    ASW_handler.send_command_and_receive("V")

    # ── Wait for plot.ps ───────────────────────────────────────────────────
    source_ps = os.path.join(base_dir, reference_folder, "plot.ps")
    target_ps = os.path.join(target_dir, "plot_" + geometry_filename.replace(".asw", ".ps"))

    print(f"[ASW_Helpers] Waiting for plot.ps to finish writing: {source_ps}")
    _wait_for_file_stable(source_ps, stable_duration, poll_interval, timeout)
    print(f"[ASW_Helpers] plot.ps is stable.")

    # ── Append extra hardcopies (workaround for glitchy last pages) ────────
    N = 3
    print(f"[ASW_Helpers] Appending {N} extra hardcopy page(s) to flush ASWING buffer...")
    for i in range(N):
        ASW_handler.send_command_and_receive("H")
    time.sleep(0.5)

    # ── Strip the glitchy trailing pages ──────────────────────────────────
    print(f"[ASW_Helpers] Removing last {N} glitchy page(s) from plot.ps...")
    _delete_last_n_pages_ps(source_ps, N)

    # ── Move to destination ────────────────────────────────────────────────
    print(f"[ASW_Helpers] Moving postscript file to video folder...")
    print(f"[ASW_Helpers]   {source_ps}")
    print(f"[ASW_Helpers]   → {target_ps}")
    shutil.move(source_ps, target_ps)
    print(f"[ASW_Helpers] Done. Postscript file ready at: {target_ps}")

    return target_ps


def _delete_last_n_pages_ps(filepath, n):
    """Remove the last n pages from a PostScript file in-place."""
    with open(filepath, "r", encoding="latin-1") as f:
        content = f.read()

    page_positions = [m.start() for m in re.finditer(r"^%%Page:", content, re.MULTILINE)]

    if n >= len(page_positions):
        print(f"[ASW_Helpers] Warning: file has {len(page_positions)} page(s), "
              f"cannot remove {n} — skipping.")
        return

    cut_position = page_positions[-n]
    truncated = content[:cut_position].rstrip() + "\n%%Trailer\n%%EOF\n"

    with open(filepath, "w", encoding="latin-1") as f:
        f.write(truncated)

    print(f"[ASW_Helpers] Page trim complete: "
          f"{len(page_positions)} → {len(page_positions) - n} pages.")


def _wait_for_file_stable(filepath, stable_duration, poll_interval, timeout):
    """Private helper — polls until filepath is unchanged for stable_duration seconds."""
    deadline = time.time() + timeout
    last_size, last_mtime = -1, -1
    stable_since = None

    while time.time() < deadline:
        if os.path.exists(filepath):
            try:
                stat = os.stat(filepath)
                size, mtime = stat.st_size, stat.st_mtime
            except OSError:
                time.sleep(poll_interval)
                continue

            if size == last_size and mtime == last_mtime:
                if stable_since is None:
                    stable_since = time.time()
                elif time.time() - stable_since >= stable_duration:
                    return
            else:
                last_size, last_mtime = size, mtime
                stable_since = None
        else:
            last_size, last_mtime = -1, -1
            stable_since = None

        time.sleep(poll_interval)

    raise TimeoutError(f"[ASW_Helpers] Timed out waiting for '{filepath}' "
                       f"to stabilise after {timeout}s")












import os
import shutil
import subprocess
import glob

def Generate_Analysis_Videos(
    ps_filepath, 
    Dt=0.02, 
    transpose=None, 
    quality="medium", 
    keep_frames=False
):
    """
    Converts a multi-page PostScript file into MP4, GIF, and WebM.
    
    Parameters
    ----------
    ps_filepath : str   - Full path to the .ps file
    Dt          : float - Seconds per frame (e.g., 0.02)
    transpose   : int   - None, 1 (90 CW), 2 (90 CCW)
    quality     : str   - "high", "medium", "low" (controls DPI and compression)
    keep_frames : bool  - If True, PNG frames are not deleted
    """
    
    # 1. Setup paths and dependencies
    _check_dependency("gs", "Ghostscript -> sudo apt install ghostscript")
    _check_dependency("ffmpeg", "FFmpeg -> sudo apt install ffmpeg")

    base_path = os.path.splitext(ps_filepath)[0]
    output_dir = os.path.dirname(ps_filepath)
    frames_dir = base_path + "_frames"
    fps = 1.0 / Dt
    
    # Quality Presets
    presets = {
        "high":   {"dpi": 300, "crf_mp4": 18, "crf_webm": 20, "width": 1200},
        "medium": {"dpi": 150, "crf_mp4": 23, "crf_webm": 30, "width": 800},
        "low":    {"dpi": 72,  "crf_mp4": 28, "crf_webm": 40, "width": 600}
    }
    cfg = presets.get(quality, presets["medium"])

    os.makedirs(frames_dir, exist_ok=True)
    frame_pattern = os.path.join(frames_dir, "frame_%04d.png")

    # 2. Step 1: Rasterize PS to PNG (Ghostscript)
    print(f"--- Rasterizing PS at {cfg['dpi']} DPI ---")
    gs_cmd = [
        "gs", "-dBATCH", "-dNOPAUSE", "-dQUIET", "-sDEVICE=png16m",
        f"-r{cfg['dpi']}", f"-sOutputFile={frame_pattern}", ps_filepath
    ]
    _run(gs_cmd, "Ghostscript failed")

    # Verify frames exist
    frames = sorted(glob.glob(os.path.join(frames_dir, "frame_*.png")))
    if not frames:
        raise RuntimeError("No frames generated. Check your .ps file.")

    # Prepare FFmpeg filters (Rotation + Padding/Scaling)
    vf_base = ""
    if transpose:
        vf_base += f"transpose={transpose},"

    # 3. Step 2: Generate MP4
    output_mp4 = base_path + ".mp4"
    print(f"--- Generating MP4 ({quality}) ---")
    mp4_vf = vf_base + "pad=ceil(iw/2)*2:ceil(ih/2)*2" # Ensure even dimensions
    mp4_cmd = [
        "ffmpeg", "-y", "-framerate", str(fps), "-i", frame_pattern,
        "-vf", mp4_vf, "-c:v", "libx264", "-crf", str(cfg['crf_mp4']),
        "-pix_fmt", "yuv420p", output_mp4
    ]
    _run(mp4_cmd, "FFmpeg MP4 failed")

    # 4. Step 3: Generate GIF (High Quality Palette)
    output_gif = base_path + ".gif"
    print(f"--- Generating GIF ({quality}) ---")
    gif_vf = (
        vf_base + 
        f"scale={cfg['width']}:-1:flags=lanczos,split[s0][s1];"
        "[s0]palettegen=stats_mode=diff[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3"
    )
    gif_cmd = [
        "ffmpeg", "-y", "-framerate", str(fps), "-i", frame_pattern,
        "-vf", gif_vf, output_gif
    ]
    _run(gif_cmd, "FFmpeg GIF failed")

    # 5. Step 4: Generate WebM
    output_webm = base_path + ".webm"
    print(f"--- Generating WebM ({quality}) ---")
    webm_cmd = [
        "ffmpeg", "-y", "-framerate", str(fps), "-i", frame_pattern,
        "-vf", vf_base.rstrip(','), # Remove trailing comma if no other filters
        "-c:v", "libvpx-vp9", "-crf", str(cfg['crf_webm']), "-b:v", "0",
        output_webm
    ]
    _run(webm_cmd, "FFmpeg WebM failed")

    # 6. Cleanup
    if not keep_frames:
        print("--- Cleaning up temporary frames ---")
        shutil.rmtree(frames_dir)
    
    print(f"Done. Files created in: {output_dir}")
    return output_mp4, output_gif, output_webm

def _check_dependency(cmd, install_hint):
    if shutil.which(cmd) is None:
        raise EnvironmentError(f"'{cmd}' not found. {install_hint}")

def _run(cmd, error_prefix):
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"{error_prefix}:\n{result.stderr.strip()}")
    




def Generate_Strobe_Plot(
    ps_filepath, 
    indices, 
    transpose=None, 
    quality="high", 
    output_suffix="_strobe",
    mask_region=[50, 2220, 1016, 2570] 
):
    _check_dependency("gs", "Ghostscript -> sudo apt install ghostscript")
    _check_dependency("ffmpeg", "FFmpeg -> sudo apt install ffmpeg")

    base_path = os.path.splitext(ps_filepath)[0]
    strobe_dir = base_path + "_strobe_temp"
    output_img = base_path + output_suffix + ".png"
    
    presets = {
        "high":   {"dpi": 300},
        "medium": {"dpi": 150},
        "low":    {"dpi": 72}
    }
    cfg = presets.get(quality, presets["medium"])
    os.makedirs(strobe_dir, exist_ok=True)

    
    # 1. Rasterize (Using standard settings that work when mask is None)
    page_list = ",".join(map(str, indices))
    frame_pattern = os.path.join(strobe_dir, "strobe_%04d.png")
    gs_cmd = [
        "gs", "-dBATCH", "-dNOPAUSE", "-dQUIET", "-sDEVICE=png16m",
        f"-r{cfg['dpi']}", f"-sPageList={page_list}",
        f"-sOutputFile={frame_pattern}", ps_filepath
    ]
    _run(gs_cmd, "Ghostscript extraction failed")

    # 2. Get frames
    extracted_frames = sorted(glob.glob(os.path.join(strobe_dir, "*.png")))
    
    # 3. Build filter chain with RGB enforcement
    inputs = []
    filter_chain = ""
    
    # CRITICAL FIX: We force the first input to RGB24 to prevent the Green shift
    filter_chain += "[0:v]format=rgb24[v0_rgb];"
    
    for i, frame in enumerate(extracted_frames):
        inputs.extend(["-i", frame])
        if i == 0: continue
        
        # We also force each subsequent frame to RGB before blending
        filter_chain += f"[{i}:v]format=rgb24[v{i}_rgb];"
        
        prev_link = "[v0_rgb]" if i == 1 else f"[blended{i-1}]"
        next_link = f"[blended{i}]"
        
        filter_chain += f"{prev_link}[v{i}_rgb]blend=all_mode=darken{next_link};"

    current_link = f"[blended{len(extracted_frames)-1}]"

    # 4. Rotation
    if transpose:
        filter_chain += f"{current_link}transpose={transpose}[transposed];"
        current_link = "[transposed]"

    # 5. Apply the White Mask (Now safe from color shifts)
    if mask_region:
        x1, y1, x2, y2 = mask_region
        w, h = abs(x2 - x1), abs(y2 - y1)
        fx, fy = min(x1, x2), min(y1, y2)
        # Added format=rgb24 again here just to be absolutely sure before drawing
        filter_chain += f"{current_link}format=rgb24,drawbox=x={fx}:y={fy}:w={w}:h={h}:color=white:t=fill[masked]"
        map_link = "[masked]"
    else:
        map_link = current_link

    # 6. Final Execution
    ffmpeg_cmd = ["ffmpeg", "-y"] + inputs + [
        "-filter_complex", filter_chain.rstrip(";"),
        "-map", map_link,
        "-pix_fmt", "rgb24", # Ensure output file is also RGB
        output_img
    ]
    _run(ffmpeg_cmd, "FFmpeg failed")

    shutil.rmtree(strobe_dir)
    return output_img


