# =============================================================================
# WingLoop — PyControl_Plot
# =============================================================================
# Copyright (c) 2024-2026 Leonardo Avoni (avonileonardo@gmail.com)
#
# This file is part of WingLoop.
# WingLoop is licensed under CC BY-NC-SA 4.0 (Non-Commercial use only).
# Full license: https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# For commercial use, contact the author: avonileonardo@gmail.com
#
# If you use WingLoop in academic work, please cite:
#   Avoni et al., "Enhancing ASWING Flight Dynamics Simulations with
#   Closed-Loop Control for Flexible Aircraft," AIAA 2025-3425.
#   https://arc.aiaa.org/doi/10.2514/6.2025-3425
# =============================================================================
"""
====================================================================================
WingLoop Library — PyControl_Plot
Live Visualization and Post-Processing Utilities for ASWING Simulations
====================================================================================

Author: Leonardo Avoni
Email: avonileonardo@gmail.com
Initial release: 08 Mar 2026
Last modified: 08 Mar 2026
------------------------------------------------------------------------------------
Overview
------------------------------------------------------------------------------------
PyControl_Plot provides real-time and post-processing visualization tools
for ASWING simulation data produced by the WingLoop framework.

The module operates on the simulation dictionaries generated by:

    PyControl_IO / PyControl_Text2Python
        initialize_data_dict()
        read_aswing_file()

These dictionaries contain time-series data of aircraft states, aerodynamic
variables, and control signals.

The plotter automatically builds a structured figure showing:

    • State variables (user-selected)
    • Control surface deflections (F1-F20)
    • Engine / actuator outputs (E1-E20)
    • Convergence diagnostics

The plotting system supports both **live monitoring during simulation** and
**post-processing visualization after simulation completion**.

------------------------------------------------------------------------------------
Main Features
------------------------------------------------------------------------------------

• Live plotting during simulation loops
• Post-processing of fully populated simulation dictionaries
• Automatic detection of actuation channels (F1-F20, E1-E20)
• Dynamic axis scaling
• Convergence monitoring with visual divergence highlighting
• Export to publication-ready PDF figures
• Non-blocking interactive plotting

------------------------------------------------------------------------------------
Typical Usage
------------------------------------------------------------------------------------

Live simulation mode:

    plotter = ASWINGLivePlotter(
        parameter_list=["earth X", "earth Y", "earth Z", "Heading", "Elev.", "Bank"],
        total_sim_time=100.0
    )

    for step in simulation_steps:
        data_dict = read_aswing_file(...)
        plotter.update(data_dict)

    plotter.export("results.pdf")

Post-processing mode:

    plotter = ASWINGLivePlotter(parameter_list=[...], total_sim_time=100.0)
    plotter.update(full_simulation_dictionary)
    plotter.export("results_post.pdf")

------------------------------------------------------------------------------------
Figure Layout
------------------------------------------------------------------------------------

The figure is divided into two main panels:

Left panel — State Variables
    Displays user-selected aircraft variables such as position, attitude,
    velocity, or aerodynamic quantities.

Right panel — Actuation Channels
    Displays detected control signals:
        F1-F20 : flap / control surface commands
        E1-E20 : engine or auxiliary outputs

Additional figure elements include:

    • Top-left information panel
        - model name
        - simulation time
        - wall-clock time

    • Convergence warning banner
        Highlights simulation intervals where ASWING reports non-convergence.

------------------------------------------------------------------------------------
Main Class
------------------------------------------------------------------------------------

ASWINGLivePlotter

Responsible for:
    • Building the figure layout
    • Updating time-series plots during simulation
    • Highlighting divergence regions
    • Exporting figures to PDF
    • Managing interactive plot updates

------------------------------------------------------------------------------------
Helper Functions
------------------------------------------------------------------------------------

plot_aswing_dict(...)
    Convenience wrapper for one-shot visualization of a simulation dictionary.
    Useful for quick post-processing scripts.

------------------------------------------------------------------------------------
Testing
------------------------------------------------------------------------------------
The module includes a standalone demonstration that generates synthetic
simulation data to validate plotting functionality.

Run the module directly to launch the demo:

    python PyControl_LivePlotter.py

------------------------------------------------------------------------------------
Notes
------------------------------------------------------------------------------------

• The plotting backend uses Matplotlib interactive mode.
• The plot window is designed not to steal focus during live simulation updates.
• Convergence intervals are detected using the `IsConverged` variable produced
  by ASWING.

====================================================================================
"""

import time
import re
import numpy as np
import matplotlib
matplotlib.use("TkAgg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.backends.backend_pdf import PdfPages


# ── helpers ──────────────────────────────────────────────────────────────────

def _detect_control_vars(model_variables: dict):
    """Return sorted lists of flap keys (F1…F20) and engine keys (E1…E20)."""
    flap_pat   = re.compile(r'^F(\d{1,2})$')
    engine_pat = re.compile(r'^E(\d{1,2})$')
    flaps   = sorted(
        [k for k in model_variables
         if flap_pat.match(k) and model_variables[k].get("values")],
        key=lambda x: int(x[1:]))
    engines = sorted(
        [k for k in model_variables
         if engine_pat.match(k) and model_variables[k].get("values")],
        key=lambda x: int(x[1:]))
    return flaps, engines


def _get_values(data_dict: dict, key: str):
    """Safe accessor - returns [] if key absent or has no values."""
    mv = data_dict.get("ModelVariables", {})
    return mv.get(key, {}).get("values", [])


def _get_unit(data_dict: dict, key: str):
    mv = data_dict.get("ModelVariables", {})
    return mv.get(key, {}).get("unit") or ""


def _compute_diverged_spans(t_arr: np.ndarray, conv_arr: np.ndarray):
    """
    Given parallel arrays of time values and boolean convergence flags,
    return a list of (t_start, t_end) intervals where the simulation was
    NOT converged.

    The span is extended half a time-step on each side so that a single
    unconverged point still produces a visible rectangle.
    """
    if len(t_arr) == 0 or len(conv_arr) == 0:
        return []

    n   = min(len(t_arr), len(conv_arr))
    t   = t_arr[:n]
    ok  = np.array(conv_arr[:n], dtype=bool)
    bad = ~ok

    if not bad.any():
        return []

    # Typical step size for half-step padding
    dt = float(np.median(np.diff(t))) * 0.5 if n > 1 else 0.0

    spans = []
    in_span = False
    t_start = None

    for i, is_bad in enumerate(bad):
        if is_bad and not in_span:
            t_start = t[i] - dt
            in_span = True
        elif not is_bad and in_span:
            spans.append((t_start, t[i - 1] + dt))
            in_span = False

    if in_span:                          # still diverged at the last sample
        spans.append((t_start, t[-1] + dt))

    return spans


# ── main class ────────────────────────────────────────────────────────────────

class ASWINGLivePlotter:
    """
    Live / post-processing plotter for ASWING simulation output dictionaries.

    Parameters
    ----------
    parameter_list : list[str]
        Variable names to show in the *State Variables* panel
        (e.g. ["earth X", "earth Y", "earth Z", "Heading", "Elev.", "Bank"]).
        Names must match keys in data_dict["ModelVariables"] (after rename_map
        is applied, i.e. use internal names).
    total_sim_time : float
        Expected total simulation time [s].  Used to pre-scale the x-axis so
        the live plot does not jump around.
    refresh_interval : float
        Minimum wall-clock seconds between figure refreshes (default 0.5 s).
        Set to 0 to redraw on every call to update().
    figsize : tuple
        Matplotlib figure size in inches.
    """

    # colour cycle for individual lines
    _COLOURS = plt.rcParams["axes.prop_cycle"].by_key()["color"]

    def __init__(
        self,
        parameter_list: list,
        total_sim_time: float,
        refresh_interval: float = 0.5,
        figsize: tuple = (16, 10),
    ):
        self.parameter_list   = list(parameter_list)
        self.total_sim_time   = float(total_sim_time)
        self.refresh_interval = refresh_interval
        self.figsize          = figsize

        self._wall_t0        = time.time()
        self._last_draw_time = -np.inf

        # figure / axes created lazily on first update() call so that the
        # caller does not need a display at import time
        self._fig       = None
        self._info_text = None   # top-left Text artist, created in _build_figure
        self._axes  = {}   # name → Axes
        self._lines = {}  # name → Line2D

        # track whether we have set up axes for actuation channels yet
        self._actuation_keys: list = []

        # convergence overlay state
        self._div_spans: list = []       # list of axvspan patches, per axes key
        self._warn_text = None           # figure-level warning Text artist

        self._ylims      = {}
        self._last_spans = []
        self._raised_once  = False  

    # ── public API ───────────────────────────────────────────────────────────

    def update(self, data_dict: dict, force_draw: bool = False):
        
        """
        Refresh the live figure with the latest contents of *data_dict*.

        May be called every simulation step (iterative mode) or just once
        after the simulation completes (post-processing mode).  The logic is
        identical either way.

        Parameters
        ----------
        data_dict   : dict  - the dictionary produced by read_aswing_file.
        force_draw  : bool  - if True, redraw regardless of refresh_interval.
        """
    
        if self._fig is None:
            self._build_figure(data_dict)

        # Raise window once on first real update; never interfere again
        if not self._raised_once and self._fig is not None:
            try:
                self._fig.canvas.manager.window.lift()
            except AttributeError:
                try:
                    self._fig.canvas.manager.window.raise_()
                except AttributeError:
                    pass
            self._raised_once = True

        # ── cache direct list references on first call ────────────────────────
        # We grab the actual list/array objects inside data_dict once, so every
        # subsequent frame just reads from them without any dict traversal.
        if not self._val_refs:
            mv = data_dict.get("ModelVariables", {})
            self._t_ref = mv.get("Time", {}).get("values", [])
            all_keys = self.parameter_list + self._actuation_keys
            for key in all_keys:
                ref = mv.get(key, {}).get("values")
                if ref is not None:
                    self._val_refs[key] = ref

        # ── update info text ──────────────────────────────────────────────────
        sim_t  = self._t_ref[-1] if self._t_ref else 0.0
        wall_t = time.time() - self._wall_t0
        self._info_text.set_text(
            f"Model:     {data_dict.get('ModelName','N/A')}\n"
            f"Sim time:  {sim_t:.3f} s / {self.total_sim_time:.1f} s\n"
            f"Wall time: {wall_t:.1f} s"
        )

        # ── build time array once per frame ──────────────────────────────────
        t_ref = self._t_ref
        n_t   = len(t_ref)
        if n_t == 0:
            return
        t_arr = np.asarray(t_ref)

        # ── check if any ylim needs expanding (triggers a full redraw) ────────
        needs_full_redraw = force_draw
        all_keys = self.parameter_list + self._actuation_keys

        for key, vals_ref in self._val_refs.items():
            n = min(n_t, len(vals_ref))
            if n == 0:
                continue
            v = vals_ref[n - 1]   # only check the newest value — O(1) not O(n)
            ymin = self._ymin.get(key,  np.inf)
            ymax = self._ymax.get(key, -np.inf)
            if v < ymin or v > ymax:
                self._ymin[key] = min(ymin, v)
                self._ymax.setdefault(key, -np.inf)
                # recompute proper margin from full slice only when range expands
                v_arr  = np.asarray(vals_ref[:n])
                vlo, vhi = float(v_arr.min()), float(v_arr.max())
                margin = (vhi - vlo) * 0.05 if (vhi - vlo) > 0 else 0.1
                self._axes[key].set_ylim(vlo - margin, vhi + margin)
                self._ymin[key] = vlo
                self._ymax[key] = vhi
                needs_full_redraw = True

        # ── update convergence overlays (only when spans actually change) ─────
        conv_vals = _get_values(data_dict, "IsConverged")
        if conv_vals:
            spans = _compute_diverged_spans(t_arr, np.array(conv_vals, dtype=bool))
            if spans != self._last_spans:
                self._update_convergence_overlays(data_dict, t_arr)
                needs_full_redraw = True

        # ── update line data ──────────────────────────────────────────────────
        for key, vals_ref in self._val_refs.items():
            n = min(n_t, len(vals_ref))
            if n == 0:
                continue
            line = self._lines.get(key)
            if line is None:
                continue
            line.set_data(t_arr[:n], np.asarray(vals_ref[:n]))

        # ── draw ──────────────────────────────────────────────────────────────
        now = time.time()
        if (now - self._last_draw_time) < self.refresh_interval and not force_draw:
            return

        canvas = self._fig.canvas
        if needs_full_redraw:
            # Full redraw required (ylim changed, new divergence, first frame).
            # Re-save background so subsequent blit frames are correct.
            canvas.draw()
            self._bg = canvas.copy_from_bbox(self._fig.bbox)
            canvas.flush_events()   # ← ADD THIS
        else:
            # ── BLIT PATH: the fast one ───────────────────────────────────
            # Restore saved background (axes, ticks, grid — everything static).
            canvas.restore_region(self._bg)
            # Draw only the line artists that changed.
            for key in all_keys:
                line = self._lines.get(key)
                ax   = self._axes.get(key)
                if line and ax:
                    ax.draw_artist(line)
            # Also redraw the info text (it changes every frame).
            self._fig.draw_artist(self._info_text)
            # Push only the changed pixels to the screen.
            canvas.blit(self._fig.bbox)
            canvas.flush_events()

        self._last_draw_time = now

    def export(self, filepath: str = "aswing_results.pdf"):
        """
        Save the current figure to *filepath* (PDF).

        Can be called after update() has been called at least once.
        If the figure does not exist yet, raises RuntimeError.
        """
        if self._fig is None:
            raise RuntimeError(
                "export() called before update(). "
                "Call update(data_dict) at least once first."
            )
        # Force a final full render
        self._fig.canvas.draw()
        with PdfPages(filepath) as pdf:
            pdf.savefig(self._fig, bbox_inches="tight")
        print(f"[PyControl_Plot] Figure saved → {filepath}")

    def close(self):
        """Close the matplotlib figure window."""
        if self._fig is not None:
            plt.close(self._fig)
            self._fig = None

    # ── private helpers ───────────────────────────────────────────────────────

    def _update_convergence_overlays(self, data_dict: dict, t_arr: np.ndarray):
        """
        Recompute diverged time spans from IsConverged and redraw red axvspan
        patches on every subplot.  Old patches are removed before new ones are
        added so there is no accumulation across update() calls.
        """
        conv_vals = _get_values(data_dict, "IsConverged")
        if not conv_vals:
            return

        spans = _compute_diverged_spans(t_arr, np.array(conv_vals, dtype=bool))

        # ── skip all patch surgery if nothing changed ─────────────────────
        if spans == self._last_spans:
            return
        self._last_spans = spans

        # ── remove previous patches ───────────────────────────────────────
        for patch in self._div_spans:
            try:
                patch.remove()
            except ValueError:
                pass   # already removed
        self._div_spans = []

        # ── draw new patches on every subplot ─────────────────────────────
        all_keys = self.parameter_list + self._actuation_keys
        for t0, t1 in spans:
            for key in all_keys:
                if key not in self._axes:
                    continue
                patch = self._axes[key].axvspan(
                    t0, t1,
                    facecolor="red", alpha=0.15,
                    zorder=0, label="_nolegend_"
                )
                self._div_spans.append(patch)

        # ── update the figure-level warning banner ────────────────────────
        if spans:
            # Build a compact summary, e.g. "⚠ Diverged: 35.0–40.0 s, 55.0–57.5 s"
            span_strs = ", ".join(f"{t0:.2g}–{t1:.2g} s" for t0, t1 in spans)
            self._warn_text.set_text(f"⚠  NOT CONVERGED: {span_strs}")
            self._warn_text.set_alpha(1.0)
        else:
            self._warn_text.set_text("")
            self._warn_text.set_alpha(0.0)

    def _build_figure(self, data_dict: dict):
        """
        Build the complete figure layout on first call.
        One subplot per tracked variable, grouped into two column-panels:
          Left  → user-requested parameter_list
          Right → detected actuation (flaps + engines)
        """

        flaps, engines = _detect_control_vars(data_dict.get("ModelVariables", {}))
        self._actuation_keys = flaps + engines

        n_left  = len(self.parameter_list)
        n_right = len(self._actuation_keys)
        n_rows  = max(n_left, n_right, 1)

        fig = plt.figure(figsize=self.figsize)
        model_name = data_dict.get("ModelName", "N/A")
        fig.canvas.manager.set_window_title(f"WingLoop: {model_name} live plot")
        fig.subplots_adjust(
            left=0.07, right=0.97,
            top=0.88, bottom=0.06,
            wspace=0.35, hspace=0.55
        )

        # Two GridSpec objects side-by-side (with a gap between them)
        gs_left  = gridspec.GridSpec(n_rows, 1, figure=fig,
                                     left=0.06, right=0.48,
                                     hspace=0.55)
        gs_right = gridspec.GridSpec(n_rows, 1, figure=fig,
                                     left=0.54, right=0.97,
                                     hspace=0.55)

        # ── left panel ────────────────────────────────────────────────────
        for i, key in enumerate(self.parameter_list):
            ax = fig.add_subplot(gs_left[i, 0])
            unit = _get_unit(data_dict, key)
            ylabel = f"{key} [{unit}]" if unit else key
            ax.set_ylabel(ylabel, fontsize=9)
            
            ax.set_xlim(0, self.total_sim_time)
            ax.tick_params(labelsize=9)
            ax.grid(True, linestyle="--", alpha=0.5)

            colour = self._COLOURS[i % len(self._COLOURS)]
            (line,) = ax.plot([], [], color=colour, linewidth=1.2)

            self._axes[key]  = ax
            self._lines[key] = line
        ax.set_xlabel("Time [s]", fontsize=9)

        # ── right panel ───────────────────────────────────────────────────
        for j, key in enumerate(self._actuation_keys):
            ax = fig.add_subplot(gs_right[j, 0])
            unit = _get_unit(data_dict, key)
            label_prefix = "Flap" if key.startswith("F") else "Engine"
            ylabel = f"{label_prefix} {key[1:]} [{unit}]" if unit else f"{label_prefix} {key[1:]}"
            ax.set_ylabel(ylabel, fontsize=9)
            
            ax.set_xlim(0, self.total_sim_time)
            ax.tick_params(labelsize=9)
            ax.grid(True, linestyle="--", alpha=0.5)

            colour = self._COLOURS[(j + n_left) % len(self._COLOURS)]
            (line,) = ax.plot([], [], color=colour, linewidth=1.2)

            self._axes[key]  = ax
            self._lines[key] = line
        ax.set_xlabel("Time [s]", fontsize=9)

        # ── column titles ─────────────────────────────────────────────────
        if n_left:
            fig.text(0.27, 0.91, "State Variables",
                     ha="center", fontsize=12, fontweight="bold")
        if n_right:
            fig.text(0.755, 0.91, "Actuation Channels",
                     ha="center", fontsize=12, fontweight="bold")
            


        # ── top-left info block (updated on every update() call) ──────────
        self._info_text = fig.text(
            0.01, 0.99, "",
            ha="left", va="top",
            fontsize=9, fontfamily="monospace",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="lightyellow",
                      edgecolor="gray", alpha=0.8)
        )

        # ── convergence warning banner (hidden until needed) ───────────────
        self._warn_text = fig.text(
            0.5, 0.97, "",
            ha="center", va="center",
            fontsize=13, fontweight="bold", color="darkred",
            alpha=0.0,                          # invisible until triggered
            bbox=dict(boxstyle="round,pad=0.4", facecolor="mistyrose",
                      edgecolor="red", linewidth=2),
            zorder=10,
        )

        # ── finalise figure ───────────────────────────────────────────────
        # self._fig must be set BEFORE any canvas call
        self._fig = fig

        plt.ion()
        plt.show()

        # Initial draw to populate the canvas; background saved for blitting
        fig.canvas.draw()
        self._bg = fig.canvas.copy_from_bbox(fig.bbox)

        # Caches filled on first update() call
        self._val_refs = {}
        self._t_ref    = None
        self._ymin     = {}
        self._ymax     = {}
        
        
# ── convenience wrapper ───────────────────────────────────────────────────────

def plot_aswing_dict(
    data_dict: dict,
    parameter_list: list,
    total_sim_time: float,
    export_path: str = None,
) -> "ASWINGLivePlotter":
    """
    One-liner post-processing helper.  Creates a plotter, calls update() once,
    optionally exports to PDF, and returns the plotter object.

    Example
    -------
    plotter = plot_aswing_dict(
        data_dict       = my_dict,
        parameter_list  = ["earth X", "earth Y", "Heading", "Bank"],
        total_sim_time  = 100.0,
        export_path     = "results.pdf",
    )
    """
    plotter = ASWINGLivePlotter(parameter_list, total_sim_time)
    plotter.update(data_dict, force_draw=True)
    if export_path:
        plotter.export(export_path)
    return plotter


# ── minimal smoke-test (no real files needed) ─────────────────────────────────
if __name__ == "__main__":

    # ── build a synthetic dictionary that mimics read_aswing_file output ──
    N = 80   # number of "timesteps" to fake
    t = np.linspace(0, 40, N)

    # Simulate divergence between t=18 s and t=26 s
    is_converged = [not (18 <= ti <= 26) for ti in t]

    def _fake_var(vals, unit=None):
        return {"values": list(vals), "unit": unit, "latex": None}

    fake_dict = {
        "ModelName": "Demo HALE Aircraft",
        "ModelStates": [],
        "ModelVariables": {
            "Time":        _fake_var(t,                                    "s"),
            "IsConverged": {"values": is_converged, "unit": None, "latex": None},
            "earth X":     _fake_var(t * 12.0,                            "m"),
            "earth Y":     _fake_var(np.sin(t * 0.3) * 5,                 "m"),
            "earth Z":     _fake_var(-t * 0.5 + np.random.randn(N)*0.2,   "m"),
            "Heading":     _fake_var(np.degrees(np.arctan(t*0.05)),        "deg"),
            "Elev.":       _fake_var(np.sin(t * 0.2) * 3,                 "deg"),
            "Bank":        _fake_var(np.cos(t * 0.15) * 8,                "deg"),
            "F1":          _fake_var(np.sin(t * 0.1) * 5,                 "deg"),
            "F2":          _fake_var(np.cos(t * 0.12) * 3,                "deg"),
            "E1":          _fake_var(9.5 + np.sin(t * 0.05),              ""),
            "E2":          _fake_var(10.5 + np.cos(t * 0.05),             ""),
            "E15":          {"values": [], "unit": None,"latex": None}
        }
    }


    param_list = ["earth X", "earth Y", "earth Z", "Heading", "Elev.", "Bank"]

    # ── iterative (live) demo ─────────────────────────────────────────────
    plotter = ASWINGLivePlotter(
        parameter_list=param_list,
        total_sim_time=40.0,
        refresh_interval=0.1,
    )

    # Replace the partial-dict loop with a growing single dict:
    live_dict = {
        "ModelName": fake_dict["ModelName"],
        "ModelStates": [],
        "ModelVariables": {
            k: {"values": [], "unit": v["unit"], "latex": v["latex"]}
            for k, v in fake_dict["ModelVariables"].items()
        }
    }

    print("Simulating live update (80 steps)…")
    for step in range(N):
        # Append one new value to each variable — mimics read_aswing_file behaviour
        for k, v in fake_dict["ModelVariables"].items():
            if step < len(v["values"]):
                live_dict["ModelVariables"][k]["values"].append(v["values"][step])
        plotter.update(live_dict)
        time.sleep(0.03)

    plotter.export("aswing_live_demo.pdf")
    print("[PyControl_Plot] Done – press Enter to close the window.")
    input()
    plotter.close()